### ISSUE TITLE
TP-Link Archer C7 v2 的openvpn 無法使用，與one key openvpn下載設定都是0kb

### ISSUE THREAD

**Issue by jackswei** [x-wrt/build-release#19]
我使用最新版的和前一年的版本都一樣，我不知要怎麼修，要請大大麻煩可以修正，感謝。
![2023-02-17_22-33-08](https://user-images.githubusercontent.com/6355204/219821225-027e0e1f-446a-43e5-87ce-ee749e2110e4.png)

**Comment by ptpt52** [comment]
openvpn客户端开启压缩 full 选项 才能通吧。

**Comment by ptpt52** [comment]
@jackswei 
there is no openvpn support for this tplink archer c7-v2, since the flash is small.

**Comment by jackswei** [comment]
感謝。
