### ISSUE TITLE
mediatek firmware

### ISSUE THREAD

**Issue by szyper-sakrona** [x-wrt/build-release#28]
Hello Ptpt52!
Thanks for adding new models (zyxel and mercursys) to builds.
I have an ask for include new firmware of mediatek wifi cards.
Could you grab all, or only mt7915modules:
https://git01.mediatek.com/plugins/gitiles/openwrt/feeds/mtk-openwrt-feeds/+/refs/heads/master/autobuild_mac80211_release/package/kernel/mt76/src/firmware

this is mt7915 version is:
----
mt7915e 0000:02:00.0: HW/SW Version: 0x8a108a10, Build Time: 20230418151304a
mt7915e 0000:02:00.0: WM Firmware Version: ____000000, Build Time: 20230418151336
mt7915e 0000:02:00.0: WA Firmware Version: DEV_000000, Build Time: 20230418151358
----
and it is running a lot better (less udp errors) than latest official repo, included in your builds. 
Anyway thanks for your x-wrt builds. I personally love fakemesh app!
Thanks!

**Comment by ptpt52** [comment]
upgraded
