### ISSUE TITLE
Radio1 missing On MT7620a & range got shortened.

### ISSUE THREAD

**Issue by jahidulislamjahid** [x-wrt/build-release#3]
### Bugs on v b202108291236 
the latest release from **Aug 29** made the system unusable. the wireless Radio1 (2.4Ghz) went missing on **Xiaomi Mi Router R3** (MT7620a) and the range for the Radio0 (5Ghz) went to like only 1 meter. Hope it'll be solved in the next update.
_note: i have already downgraded to a previous release. that works like charm._

**By the way Please provide a RELEASE NOTE or any kind of UPDATE LOG ** so that we can know what changed where.

**Comment by ptpt52** [comment]
@jahidulislamjahid 
Please help test this firmware
v1: 
```
http://downloads.x-wrt.com/rom/Downloads/x-wrt-9.0-b202108291236-ramips-mt7620-xiaomi_miwifi-r3-squashfs-sysupgrade-v1.bin
```

v2:
```
http://downloads.x-wrt.com/rom/Downloads/x-wrt-9.0-b202108291236-ramips-mt7620-xiaomi_miwifi-r3-squashfs-sysupgrade-v2.bin
```

which one is bad or good?
check the mac address.

**Comment by jahidulislamjahid** [comment]
### Solved.
Both firmware you gave here **V1** & **V2** works fine. for rechecking the issue i flashed the **OG** (the Buggy One) once again and faced same issue. So the firmware uploaded in the xwrt download section is definitely a Buggy one. I'm providing you some screenshots to verify the issue. 
**OG** **Buggy one**
[https://mega.nz/file/qlZhQArC#pMq94RpGsGm3H1bkz_fEgpjxjXW5te12FmVA3Ge9OHY](url)

**V1**
[https://mega.nz/file/ClYlWSxZ#fOdimcBV_RP8RnbTZFHySRr585iDO-_xyIGqlw_cQAc](url)

**V2**
[https://mega.nz/file/25IjQSCS#VehHpR3llzaGoJWtZTPHhB1uop0FzqPMPEm1xvqzePA](url)

And dude I appreciate Your effort. **Thank You Very Much.**
