### ISSUE TITLE
X-WRT x86 no space left on device 

### ISSUE THREAD

**Issue by bachvnnvn** [x-wrt/build-release#46]
Hi,

I flashed the **x-wrt-docker-24.04-b202406060001-x86-64-generic-ext4-combined-efi.img.gz** to my NVME 512GB.

It is able to boot up but I cannot do anything. When I try to change the password, it says "no space left on device"

I tried several olders rom and got the same issue.

Any suggestion?

Thanks!

**Comment by ptpt52** [comment]
how u flash it?

**Comment by bachvnnvn** [comment]
I used https://etcher.balena.io/

It works fine with OpenWrt

**Comment by ptpt52** [comment]
try https://rufus.ie/

and `df -h` see the log

**Comment by ptpt52** [comment]
or try x-wrt-24.04-b202406060001-x86-64-generic-ext4-combined-efi.img.gz first. if this also issue. then it is issue on how you flash it.

**Comment by bachvnnvn** [comment]
I tried  x-wrt-24.04-b202406060001-x86-64-generic-ext4-combined-efi.img.gz with Rufus. Still no space left.

![image](https://github.com/x-wrt/build-release/assets/54640122/cefec668-6b10-4299-8ca8-271a5f2833d4)
![image](https://github.com/x-wrt/build-release/assets/54640122/82215cc5-44db-4a1e-a59a-fbe2f50fdb1a)
![image](https://github.com/x-wrt/build-release/assets/54640122/43d35f8e-01e4-43e3-bc08-c10ffa5a92df)

**Comment by ptpt52** [comment]
do a full image write.

**Comment by bachvnnvn** [comment]
Sorry, what option allows me to do that with Rufus?
I cannot find that option.

Thank you!

**Comment by bachvnnvn** [comment]
Update: Changing the password directly with "passwd" doesn't work. I needed to do that through SSH.

It is working fine now.
