### ISSUE TITLE
OPKG issued due to openwrt change from ipk to apk

### ISSUE THREAD

**Issue by congphat1998** [x-wrt/build-release#55]
![image](https://github.com/user-attachments/assets/1828f55a-c943-4d48-bf33-85392dbda342)
Version
Powered by [LuCI Master (24.312.08150~ea45933)](https://github.com/openwrt/luci) / [X-WRT 24.04_b202411071136 (r28213+1-f422e381101)](https://x-wrt.com/)

**Comment by congphat1998** [comment]
Hi @ptpt52 , if you read this, please take a look at it , thanks

**Comment by menesc** [comment]
I find a temporary solution like installing necessary updates manually  (also dependencies one by one ) from "https://downloads.openwrt.org/releases/" folder by your device chip. Than;

Software/ "configure opkg",
edit "/etc/opkg/distfeeds.conf"

for 7620 (mips_24kc);

src/gz x-wrt_core https://downloads.openwrt.org/releases/packages-24.10/mipsel_24kc/packages/
src/gz x-wrt_base https://downloads.openwrt.org/releases/packages-24.10/mipsel_24kc/base/
src/gz x-wrt_luci https://downloads.openwrt.org/releases/packages-24.10/mipsel_24kc/luci/
src/gz x-wrt_packages https://downloads.openwrt.org/releases/packages-24.10/mipsel_24kc/packages/

After this i have full software list.

Note: Dependencies are in one of 4 folders, you have to search each one.

**Comment by ptpt52** [comment]
x-wrt would switch to use apk instead of opkg in next release

**Comment by congphat1998** [comment]
> I find a temporary solution like installing necessary updates manually (also dependencies one by one ) from "https://downloads.openwrt.org/releases/" folder by your device chip. Than;
> 
> Software/ "configure opkg", edit "/etc/opkg/distfeeds.conf"
> 
> for 7620 (mips_24kc);
> 
> src/gz x-wrt_core https://downloads.openwrt.org/releases/packages-24.10/mipsel_24kc/packages/ src/gz x-wrt_base https://downloads.openwrt.org/releases/packages-24.10/mipsel_24kc/base/ src/gz x-wrt_luci https://downloads.openwrt.org/releases/packages-24.10/mipsel_24kc/luci/ src/gz x-wrt_packages https://downloads.openwrt.org/releases/packages-24.10/mipsel_24kc/packages/
> 
> After this i have full software list.
> 
> Note: Dependencies are in one of 4 folders, you have to search each one.

**Comment by congphat1998** [comment]
src/gz x-wrt_core http://downloads.openwrt.org/releases/packages-24.10/x86_64/packages
src/gz x-wrt_base http://downloads.openwrt.org/releases/packages-24.10/x86_64/base
src/gz x-wrt_luci http://downloads.openwrt.org/releases/packages-24.10/x86_64/luci
src/gz x-wrt_packages http://downloads.openwrt.org/releases/packages-24.10/x86_64/packages
src/gz x-wrt_routing http://downloads.openwrt.org/releases/packages-24.10/x86_64/routing
src/gz x-wrt_telephony http://downloads.openwrt.org/releases/packages-24.10/x86_64/telephony
