### ISSUE TITLE
Need Package Installation Unlocked

### ISSUE THREAD

**Issue by jahidulislamjahid** [x-wrt/build-release#6]
### Unlock The Open Package Manager.
Hey dev! can u not lock the **package installation**  on the firmwares. we need some packages to get some specific features like **OPEN-WRT.** So please **unlock** the package installation feature.

**Comment by ptpt52** [comment]
1. login web ui and enable ssh login
2. login ssh and exec `sed -i 's/-hidden//g' /usr/share/luci/menu.d/luci-app-opkg.json`

so to unlock software package menu

**Comment by jahidulislamjahid** [comment]
### thanks !
**worked on the first try.**
